### ISSUE TITLE
边的label位置错误

### ISSUE THREAD

**Issue by fanyetu** [wenyuan/cceditor#23]
# 边的label位置错误

填写边的label之后能在界面上显示，但是label的位置却是错误的，所有的边的label都集中到了同一个位置。

![image](https://user-images.githubusercontent.com/12474097/148505081-f1cafd9a-975e-4829-a182-a02c43d21c36.png)

**Comment by wenyuan** [comment]
经过排查，这个 Bug 疑似官方版本在 4.3.0 后引入的，可以确认 4.3.0 之前是正常的，已经向官方提交 Issues：
* https://github.com/antvis/G6/issues/3428

**Comment by wenyuan** [comment]
经过初步排查，该 bug 疑似官方在 @antv/g6@4.3.0 后引入的，可以确认的是 4.3.0 之前的版本不存在该问题。现已提交 Issues 至 G6 团队：
* https://github.com/antvis/G6/issues/3428

@fanyetu

**Comment by fanyetu** [comment]
> 
降低版本后该问题不再出现，谢谢。

**Comment by wenyuan** [comment]
> > 
> 
> 降低版本后该问题不再出现，谢谢。

在我的工程中，如果降低版本到 4.3.7 可以临时解决该问题。我会继续跟进后续版本的修复情况。
