### ISSUE TITLE
bugs(面板无法点击拖拽):在预览界面点击编辑按钮后，首次进入编辑界面无法拖拽节点

### ISSUE THREAD

**Issue by aiyoudiao** [wenyuan/cceditor#7]
如题目：
![image](https://user-images.githubusercontent.com/60660505/95537369-228f9b00-0a20-11eb-8a39-45b65c4a8ace.png)
![image](https://user-images.githubusercontent.com/60660505/95537390-3509d480-0a20-11eb-9aee-2ca8dcb547f9.png)
解决办法：
![image](https://user-images.githubusercontent.com/60660505/95538336-92058a80-0a20-11eb-9ecb-003a645bb6fd.png)

**Comment by wenyuan** [comment]
感谢您找到的 bug 和提供的解决方案，已修复。 @aiyoudiao

**Comment by wenyuan** [comment]
fix in https://github.com/wenyuan/cceditor/commit/4d4686c03c86158cb20851643fd13ae1e2f88b9f
